name       : python-oauth2client
version    : 4.1.3
release    : 1
source     :
    - https://files.pythonhosted.org/packages/a6/7b/17244b1083e8e604bf154cf9b716aecd6388acd656dd01893d0d244c94d9/oauth2client-4.1.3.tar.gz : d486741e451287f69568a4d26d70d9acd73a2bbfa275746c535b4209891cccc6
license    : Apache-2.0
component  : programming.python
summary    : OAuth 2.0 client library
description: |
    oauth2client is a client library for OAuth 2.0.

    Note - oauth2client is now deprecated. No more features will be added to the
    libraries and the core team is turning down support. We recommend you use google-auth and oauthlib.

    This is, however, still required for python-pyside2
rundeps    :
    - python-asn1-modules
    - python-httplib2
    - python-rsa
    - python-six
build      : |
    %python3_setup
install    : |
    %python3_install
